Generate neg name if not specified in autoneg annotation
GoogleCloudPlatform/gke-autoneg-controller pull request #44
Opened 2021-08-12 06:56 UTC by fdfzcq

We (Fabric/Spotify) would like to use autoneg without specifying neg names and realized that the default values might be too simple and prone to name collisions. Currently the NEG name defaults to `service name + port` when using new autoneg annotation and `service name` when using old config, in this PR we propose to change it to `<namespace>-<name>-<port>-<hash>` similar to [how `k8s-io/ingress-gce` generates NEG names](https://github.com/kubernetes/ingress-gce/blob/4cb04408a6266b5ea00d9567c6165b9235392972/pkg/utils/namer/namer.go#L431-L449).

2021-08-12 07:07 UTC, fdfzcq commented on controllers/utils.go
> +func generateNegName(namespace string, name string, portStr string) string {
Erik suggested that we could import `k8s-io/ingress-gce` and call [`Namer`](https://github.com/kubernetes/ingress-gce/blob/4cb04408a6266b5ea00d9567c6165b9235392972/pkg/utils/namer/namer.go) directly. I tried this at first and got [this error](https://github.com/kubernetes/kubernetes/issues/90358), suggesting using `k8s-io/ingress-gce` as a dependency is discouraged. There is a workaround linked in the issue but it's neater to move the functionalities here.

2021-08-12 07:54 UTC, rosmo commented
Hey @fdfzcq and thank you for the PR! I was wondering if this could be a bit more flexible and I had two ideas in mind: 
- Allow passing a template to the controller via command line parameters (eg. `{namespace}-{name}-{port}-{hash}`), and/or:
- Allow setting/overriding the template via annotation on the namespace

I think the first one ought to be fairly trivial, so I'd probably go with that (would also allow to keep backwards compatibility, if the default template was `{name}-{port}`), second one I'm not so sure of (if it's even desirable). Wdyt?

2021-08-12 08:52 UTC, fdfzcq commented
Thanks @rosmo 
That sounds good, do you mean supporting something like `--neg-name-template={name}-{port}-{hash}` [here](https://github.com/GoogleCloudPlatform/gke-autoneg-controller/blob/master/deploy/autoneg.yaml#L200) ?

2021-08-13 09:20 UTC, fdfzcq commented
@rosmo I've added configurable template, could you take a look when you have time? Thanks! :)

2021-08-16 12:02 UTC, rosmo commented on main.go
> +		err = errors.New(fmt.Sprintf("invlaid neg name template %s", negNameTemplate))
Small typo here (`invlaid`) :)

2021-08-16 12:22 UTC, soellman commented on main.go
> +		err = errors.New(fmt.Sprintf("invlaid neg name template %s", negNameTemplate))
Consider using fmt.Errorf instead:
https://pkg.go.dev/fmt#Errorf

2021-08-16 12:45 UTC, soellman commented
Thanks Sophy! I'll review this tomorrow.

Question - would you also want a flag that disallows setting the service name? I could see how that might be desirable so that all users would have their service names automatically determined.

2021-08-16 12:56 UTC, fdfzcq commented
@soellman Thank you Oliver, yes we think something to disallow setting the service name would be nice to have.

2021-08-17 08:51 UTC, soellman requested changes
This is a solid and clear PR, thank you, this look great.

I have one request that will require some name changes: please let's change "neg name template" to "service name template" everywhere, as this better describes what we'll use the name to describe. We could also change the command line flag to "default-backendservice-name" as well.

If you like, you could also add a flag that disables the ability to specify a service name (something like --disable-supplied-service-names), or we can add this in a future PR.

Thanks!

2021-08-17 08:51 UTC, soellman commented on main.go
> +	flag.StringVar(&negNameTemplate, "neg-name-template", "{name}-{port}",
Let's rename this to something like "default-service-name" instead, since this is specifying the default service name.

2021-08-17 09:58 UTC, fdfzcq commented
Thanks @soellman I've changed the flag to `default-backendservice-name` now and we can make another PR to add disable-service-name flag.

2021-08-17 09:58 UTC, fdfzcq commented
@googlebot I signed it!

2021-08-17 11:41 UTC, soellman commented on main.go
> +		err = fmt.Errorf("invlaid service name template %s", serviceNameTemplate)
small typo

2021-08-17 11:43 UTC, fdfzcq commented on main.go
> +		err = fmt.Errorf("invlaid service name template %s", serviceNameTemplate)
oops thx, I forgot this :D

2021-08-17 11:46 UTC, soellman approved these changes
Looks great, thanks again for the contribution!

2021-08-17 11:49 UTC, merged